title  : Raw
author : George K. Moschovitis
summary: Intuitive Web 2.0 application framework
description:
  Raw provides everything you need to develop professional Web
  applications using Ruby and Javascript. Raw redefines Rapid 
  Application Development by providing a clean, yet efficient API
  and a layer of domain specific languages implemented on top of 
  Ruby. Raw is Web 2.0 ready, featuring excellent support for 
  AJAX, XML, Syndication while staying standards compliant. Raw 
  is part of the Nitro Mega Framework.

homepage: http://www.nitroproject.org

document: true

dependency:
  - ["glue", "= 0.50.0"]
  - ["RedCloth", ">= 3.0.4"]

index_file: main.rb

lib_path:
  - lib/raw

