module Raw

# Cleanup the xhtml code generated by REXML used in other 
# filters.

class CleanupFilter
  
  def apply(source)
    source = source.dup

    elements = "input|img|br|hr|link|style|render|include|inject|base|meta"
    source.gsub! /<textarea ([^>]*)><\/textarea>/, '<textarea \1>#{}</textarea>'
    source.gsub! /<(#{elements}) ([^>]*)><\/\1>/, '<\1 \2 />'
    source.gsub! /<(#{elements})><\/\1>/, '<\1 />'

    return source
  end
  
end

end
